var CFG=window.CFG;var CMN=window.CMN;var SYS=window.SYS;var MOCK=window.MOCK;var DTS=DTS||{};
DTS.xml=null;DTS.json=null;DTS.autoRefreshId=null;DTS.isSyncWithMyClock=false;DTS.isSyncWithInternet=false;
DTS.isLoading=false;DTS.skipBlur=false;DTS.skipFocus=false;DTS.isAdminLevel=CMN.isAdminLevel();
DTS.cnt=0;DTS.dtpicker=$("#datetimepicker");DTS.msgs={DATETIME_CANNOT_BE_UPDATED:{key:"DTS",id:1}};
DTS.RefreshUnits={Milliseconds:1,Seconds:2,Minutes:3,Hours:4,Days:5,Weeks:6};DTS.TimeObject=function(a,b){this.timeValue=a;
this.units=b;};DTS.init=function(){DTS.dtpicker.datetimepicker({dateFormat:SYS.getDateFormat(),timeFormat:SYS.getTimeFormat(),buttonImage:"grid/images/calendar.gif",buttonImageOnly:true,currentText:"Now",closeText:"Done",parse:"loose",showButtonPanel:true,showTimezone:false,showMillisec:false,showMicrosec:false,showOn:"button",timezone:null,onSelect:function(){SYS.enableSaveAndResetButtons(this);
},beforeShow:function(){DTS.skipFocus=true;DTS.stopAutoRefresh();},onClose:function(){DTS.skipBlur=true;
DTS.startAutoRefresh();}});};$("ul.css-tabs").on("tabChanged",function(a,b){if(b===2){DTS.startAutoRefresh();
}else{DTS.stopAutoRefresh();}});$("select#sys_cboMachineTimeZone").change(function(){DTS.showOrHideIsAutoDst();
DTS.enableDatetimePicker(true);SYS.enableSaveAndResetButtons(this);});DTS.dtpicker.prop("readOnly",true);
DTS.dtpicker.bind("keypress keydown",function(a){if(a.keyCode!==9&&a.keyCode!==13){a.preventDefault();
a.stopImmediatePropagation();return false;}return true;});DTS.onFocus=function(){if(DTS.skipFocus){DTS.skipFocus=false;
return;}CMN.debugLog("DTS.onFocus");if(!DTS.dtpicker.datepicker("widget").is(":visible")){DTS.startAutoRefresh();
}};DTS.onBlur=function(){if(DTS.skipBlur){DTS.skipBlur=false;return;}CMN.debugLog("DTS.onBlur");
DTS.stopAutoRefresh();};DTS.startAutoRefresh=function(){if(CFG.getCurrentTabId()!=="SYS"){return;
}DTS.cnt=0;CMN.debugLog("DTS.startAutoRefresh");window.clearTimeout(DTS.autoRefreshId);
DTS.autoRefreshId=window.setInterval(function(){if(DTS.isSyncWithMyClock){DTS.dtpicker.datetimepicker("setDate",new Date());
}else{if(!(SYS.isSaveEnabled||DTS.isLoading)){if(--DTS.cnt>0){var a=CMN.millisecondsToDate(Date.parse(DTS.dtpicker.datetimepicker("getDate"))+1000);
DTS.dtpicker.datetimepicker("setDate",a);}else{DTS.loadData(true);DTS.cnt=30;}}}},1000);
};DTS.stopAutoRefresh=function(){CMN.debugLog("DTS.stopAutoRefresh");window.clearTimeout(DTS.autoRefreshId);
DTS.autoRefreshId=null;};DTS.loadData=function(a){DTS.isLoading=true;$.ajax({type:"GET",url:"/services/network/datetimesettings",dataType:"json",async:false,cache:false,success:function(b){DTS.loadFromJson(b,a);
},error:function(b){if(b.status===12029){DTS.stopAutoRefresh();}else{CFG.handleError(b);
}}});DTS.isLoading=false;};DTS.loadFromJson=function(c,b){var a=CMN.millisecondsUtcToDate(c.machinedatetime);
DTS.dtpicker.datetimepicker("setDate",a);DTS.json=c;if(!b){$("#sys_cboMachineTimeZone").prop("selectedIndex",parseInt(c.machinetimezone,10));
$("#sys_chkIsAutoDst").prop("checked",c.isautodst!=="0");DTS.showOrHideIsAutoDst();
SYS.setInitialFocus();DTS.startAutoRefresh();}};DTS.saveData=function(){var a=DTS.getJsonFromPage();
if(CMN.compare(a,DTS.json)){return;}$.ajax({type:"PUT",url:"/services/network/datetimedata",dataType:"json",headers:{"x-auth-token":localStorage.accessToken,"Content-Type":"application/json"},global:false,async:false,data:JSON.stringify(a),complete:function(b){if(b.status===200){DTS.loadData();
}},error:function(b){CFG.handleError(b);}});};DTS.getJsonFromPage=function(){var b=DTS.dtpicker.datetimepicker("getDate");
var d=CMN.dateToMillisecondsUtc(b);var e=document.getElementById("sys_cboMachineTimeZone").selectedIndex;
var a=$("#sys_chkIsAutoDst").is(":checked")?1:0;var c={machinedatetime:d,machinetimezone:e,isautodst:a};
return c;};DTS.loadTimeZoneListCombobox=function(){$.ajax({type:"GET",url:"/services/network/timezonelist?lang="+CFG.getLanguage(),dataType:"json",async:false,success:function(a){DTS.loadTimeZoneListComboboxFromData(a);
},error:function(a){CFG.handleError(a);}});};DTS.loadTimeZoneListComboboxFromData=function(a){var c=$("#sys_cboMachineTimeZone");
for(var b in a){c.append('<option value="'+a[b].offset+","+a[b].dst+'">'+a[b].displayname+"</option>");
}};DTS.loadInternetTimeServerCombobox=function(){var a="/services/network/internettimeservers";
$.ajax({type:"GET",url:a,dataType:"json",async:false,success:function(b){DTS.loadInternetTimeServerComboboxFromData(b);
},error:function(b){CFG.handleError(b);}});};DTS.loadInternetTimeServerComboboxFromData=function(a){var c=$("#sys_selInternetTimeServer");
for(var b in a){c.append('<option value="'+a[b].displayname+'">'+a[b].displayname+"</option>");
}};DTS.loadRefreshUnitsCombobox=function(){var b="/services/network/refreshunits?lang="+CFG.getLanguage();
var a="xml";$.ajax({type:"GET",url:b,dataType:a,async:false,success:function(c){DTS.loadRefreshUnitsComboboxFromData(c,a);
},error:function(c){CFG.handleError(c);}});};DTS.loadRefreshUnitsComboboxFromData=function(a,b){var d=$("#sys_cboRefreshUnits");
if(b==="xml"){$(a).find("ArrayOfRefreshUnit").find("RefreshUnit").each(function(){d.append('<option value="'+$(this).attr("Index")+'">'+$(this).attr("DisplayName")+"</option>");
});}else{for(var c in a){d.append('<option value="'+a[c].index+'">'+a[c].displayname+"</option>");
}}};DTS.syncWithMyClock=function(a){if(a.checked){$("#sys_chkIsSyncWithInternet").prop("checked",false);
DTS.isSyncWithInternet=false;$("#sys_cboMachineTimeZone").prop("selectedIndex",DTS.getBrowserTimeZoneIndex());
DTS.showOrHideIsAutoDst();$("#sys_grpSyncWithInternet").css("display","none");}DTS.isSyncWithMyClock=a.checked;
DTS.enableMachineTimeZone(!a.checked||DTS.isSyncWithInternet);DTS.enableDatetimePicker();
SYS.enableSaveAndResetButtons(a);DTS.startAutoRefresh();$("#sys_btnSave").focus();
return true;};DTS.syncWithInternet=function(a){if(a.checked){$("#sys_chkIsSyncWithMyClock").prop("checked",false);
DTS.isSyncWithMyClock=false;$("#sys_grpSyncWithInternet").css("display","block");
}else{$("#sys_grpSyncWithInternet").css("display","none");}DTS.isSyncWithInternet=a.checked;
DTS.enableMachineTimeZone(true);DTS.enableDatetimePicker();SYS.enableSaveAndResetButtons(a);
DTS.startAutoRefresh();$("#sys_btnSave").focus();return true;};DTS.enableMachineTimeZone=function(c){var a=CMN.isAdminLevel();
var b=!a||!c;$("#sys_cboMachineTimeZone").prop("disabled",b);if(b){$("#sys_cboMachineTimeZone").css("background-color","white").css("border","#707070 thin solid");
}if(!a){$("#sys_chkIsAutoDst").prop("disabled",true);}};DTS.enableDatetimePicker=function(b){var a=CMN.isAdminLevel();
if(!b){b=!$("#sys_chkIsSyncWithMyClock").prop("checked")&&!$("#sys_chkIsSyncWithInternet").prop("checked");
}$(".ui-datepicker-trigger").prop("disabled",!a||!b);$("#datetimepicker").datepicker("option","disabled",!a||!b);
DTS.dtpicker.prop("disabled",true).css("background-color","white").css("border","#707070 thin solid");
};DTS.showOrHideIsAutoDst=function(){var a=(parseInt(document.getElementById("sys_cboMachineTimeZone").value.slice(-1),10)===1);
if(a){$("#sys_chkIsAutoDst, #sys_lblIsAutoDst").show();}else{$("#sys_chkIsAutoDst, #sys_lblIsAutoDst").hide();
}};DTS.timeToMilliseconds=function(a,b){if(b===DTS.RefreshUnits.Seconds){return a*1000;
}if(b===DTS.RefreshUnits.Minutes){return a*1000*60;}if(b===DTS.RefreshUnits.Hours){return a*1000*60*60;
}if(b===DTS.RefreshUnits.Days){return a*1000*60*60*24;}if(b===DTS.RefreshUnits.Weeks){return a*1000*60*60*24*7;
}return a;};DTS.millisecondsToTime=function(a){if(a%(1000*60*60*24*7)===0){a=a/(1000*60*60*24*7);
return new DTS.TimeObject(a,DTS.RefreshUnits.Weeks);}if(a%(1000*60*60*24)===0){a=a/(1000*60*60*24);
return new DTS.TimeObject(a,DTS.RefreshUnits.Days);}if(a%(1000*60*60)===0){a=a/(1000*60*60);
return new DTS.TimeObject(a,DTS.RefreshUnits.Hours);}if(a%(1000*60)===0){a=a/(1000*60);
return new DTS.TimeObject(a,DTS.RefreshUnits.Minutes);}if(a%1000===0){a=a/1000;return new DTS.TimeObject(a,DTS.RefreshUnits.Seconds);
}return new DTS.TimeObject(a,DTS.RefreshUnits.Milliseconds);};DTS.getBrowserTimeZoneIndex=function(){var k=new Date();
var e=new Date(k.getFullYear(),0,1,0,0,0,0);var g=new Date(k.getFullYear(),6,1,0,0,0,0);
var n=e.toGMTString();var f=new Date(n.substring(0,n.lastIndexOf(" ")-1));n=g.toGMTString();
var h=new Date(n.substring(0,n.lastIndexOf(" ")-1));var m=(e-f)/(1000*60);var a=(g-h)/(1000*60);
var b;if(m===a){b="0";}else{b="1";var c=m-a;if(c>=0){m=a;}}var l=document.getElementById("sys_cboMachineTimeZone");
if(l){var d;var j=m+","+b;for(d=0;d<l.options.length;d++){if(l.options[d].value===j){return d;
}}}return -1;};if(CMN.isIE()){document.onfocusin=DTS.onFocus;document.onfocusout=DTS.onBlur;
}else{window.onfocus=DTS.onFocus;window.onblur=DTS.onBlur;}DTS.loadTimeZoneListCombobox();
DTS.loadInternetTimeServerCombobox();DTS.loadRefreshUnitsCombobox();