var CMN=window.CMN;var CFG=window.CFG;var MOCK=window.MOCK;var INT={};INT.xml=null;
INT.msgs={PROXY_MIN_LEN_PROXYHOST:{key:"INT",id:1},PROXY_REQUIRED_PROXYHOST:{key:"INT",id:2},PROXY_MIN_LEN_PROXYPORT:{key:"INT",id:3},PROXY_REQUIRED_PROXYPORT:{key:"INT",id:4}};
$("#int_btnHelp").on("click",function(){window.open("help/internetsettings.htm");
return false;});$("#int_txtProxyHost").contextDelete({cut:function(a){INT.enableSaveAndResetButtons(a);
},paste:function(a){INT.enableSaveAndResetButtons(a);},contextDelete:function(a){INT.enableSaveAndResetButtons(a);
}});$("#int_txtProxyPort").contextDelete({cut:function(a){INT.enableSaveAndResetButtons(a);
},paste:function(a){INT.enableSaveAndResetButtons(a);},contextDelete:function(a){INT.enableSaveAndResetButtons(a);
}});$("#int_chkIsProxyEnabled").on("click",function(a){INT.enableDisableProxyInputs();
INT.enableSaveAndResetButtons(a);$("#int_txtProxyHost, #int_txtProxyPort").valid();
return true;});$("#int_chkIsBypassLocal").on("click",function(a){INT.enableSaveAndResetButtons(a);
return true;});$("#int_txtProxyHost").bind("keypress keydown",function(a){if(CMN.processKey(a,"alphanumeric")){INT.enableSaveAndResetButtons(a);
}});$("#int_txtProxyPort").bind("keypress keydown",function(a){if(CMN.processKey(a,"numeric")){INT.enableSaveAndResetButtons(a);
}});$("#int_txtProxyHost, #int_txtProxyPort").bind("cut paste",function(a){if(CMN.processCutPaste(a,a.target.id==="int_txtProxyHost"?"alphanumeric":"numeric")){INT.enableSaveAndResetButtons(a);
}});$("#int_btnSave").on("click",function(){if(!$("#frmInternetSettings").valid()){CFG.showInvalid();
return false;}CFG.performFunction(INT.savePage,CFG.getCaption(CMN.msgs.SAVING));return false;
});$("#int_btnRefresh, #int_btnReset").on("click",function(){var a=$("#int_btnSave").is(":disabled")?CMN.msgs.REFRESHING:CMN.msgs.RESETTING;
CFG.performFunction(INT.loadPage,CFG.getCaption(a));return false;});INT.makeSecure=function(){$("#int_chkIsProxyEnabled, #int_chkIsBypassLocal").prop("disabled",!CMN.isAdminLevel());
INT.enableDisableProxyInputs();};INT.enableDisableProxyInputs=function(){$("#int_txtProxyHost, #int_txtProxyPort").prop("disabled",!INT.isProxyEnabledChecked());
};INT.enableSaveAndResetButtons=function(a){$("#int_btnSave").prop("disabled",false);
$("#int_btnRefresh").addClass("hidden");$("#int_btnReset").removeClass("hidden");
CMN.validateMe(a);};INT.disableSaveAndResetButtons=function(){$("#int_btnSave").prop("disabled",true);
$("#int_btnReset").addClass("hidden");$("#int_btnRefresh").removeClass("hidden");
};INT.isProxyEnabledChecked=function(){return($("#int_chkIsProxyEnabled").is(":checked"));
};INT.loadPage=function(){var b="/services/network/internetsettings?lang="+CFG.getLanguage();
var a="xml";$.ajax({type:"GET",url:b,dataType:a,async:false,cache:false,success:function(c){INT.loadPageFromData(c);
},error:function(c){CFG.handleError(c);}});};INT.loadPageFromData=function(a,b){if(b==="xml"){CFG.setLabelsAndTitles(a);
var c=$(a).find("InternetSettings").find("Data");$("#int_chkIsProxyEnabled").prop("checked",(c.find("IsProxyEnabled").text().toLowerCase()==="true"));
$("#int_txtProxyHost").val(c.find("ProxyHost").text());$("#int_txtProxyPort").val(c.find("ProxyPort").text());
$("#int_chkIsBypassLocal").prop("checked",(c.find("IsBypassLocal").text().toLowerCase()==="true"));
INT.enableDisableProxyInputs();INT.disableSaveAndResetButtons();INT.xml=xml;}else{console.log("Not implemented.");
}};INT.savePage=function(){var a="/services/network/internetdata";var b=INT.getXmlFromPage();
if(MOCK.isMockMode()){INT.loadPage();}else{$.ajax({type:"PUT",url:a,contentType:"text/xml",global:false,async:false,data:CMN.getDataXml(b),complete:function(c){if(c.status===200){INT.loadPage();
}},error:function(c){CFG.handleError(c);}});}};INT.getXmlFromPage=function(){var b=$("#int_chkIsProxyEnabled").is(":checked")?"true":"false";
var a=$("#int_chkIsBypassLocal").is(":checked")?"true":"false";var c=CMN.cloneXmlDoc(INT.xml);
$(c).find("IsProxyEnabled").text(b);$(c).find("ProxyHost").text($("#int_txtProxyHost").val());
$(c).find("ProxyPort").text($("#int_txtProxyPort").val());$(c).find("IsBypassLocal").text(a);
return c;};INT.IsValidProxyPort=function(a){return a===""||a===0||(a>9&&a<=99999);
};INT.$container=$("#frmInternetSettings div.errcontainer");INT.$validator=$("#frmInternetSettings").validate({debug:true,errorContainer:INT.$container,errorLabelContainer:$("ol",INT.$container),errorClass:"invalid",validClass:"valid",wrapper:"li"});
INT.addValidatorRules=function(){var a=$("#int_txtProxyHost");a.rules("remove");a.rules("add",{required:{depends:function(){return INT.isProxyEnabledChecked();
}},minlength:{depends:function(){return INT.isProxyEnabledChecked();},param:4},messages:{required:CFG.lookup(INT.msgs.PROXY_REQUIRED_PROXYHOST),minlength:CFG.lookup(INT.msgs.PROXY_MIN_LEN_PROXYHOST)}});
a=$("#int_txtProxyPort");a.rules("remove");a.rules("add",{required:{depends:function(){return INT.isProxyEnabledChecked();
}},minlength:{depends:function(){return INT.isProxyEnabledChecked();},param:2},messages:{required:CFG.lookup(INT.msgs.PROXY_REQUIRED_PROXYPORT),minlength:CFG.lookup(INT.msgs.PROXY_MIN_LEN_PROXYPORT)}});
};CFG.performFunction(function(){INT.loadPage();},CFG.getCaption(CMN.msgs.LOADING));
