var CFG=window.CFG;var CMN=window.CMN;var IPA=window.IPA;var MOCK=window.MOCK;var NET=NET||{};
NET.xml=null;NET.json={};NET.isReconnected=false;NET.info={oldIpAddress:"",newIpAddress:"",isNewIpForLogin:false,isChangedToDynamic:false,isChangedToStatic:false,showConfirmTime:CMN.dateToMilliseconds()};
NET.msgs={ADAPTER_CHANGE:{key:"NET",id:1},ATTEMPTING_RECONNECT:{key:"NET",id:2},CHANGES_TO_TAKE_EFFECT:{key:"NET",id:3},CONN_CHANGING_FROM:{key:"NET",id:4},COULD_NOT_RECONNECT:{key:"NET",id:5},IPADDRESS_MUST_CONTAIN_IPADDRESS:{key:"NET",id:8},IPADDRESS_MUST_CONTAIN_SUBNETMASK:{key:"NET",id:9},IPADDRESS_EMPTY_OR_CONTAIN_DEFAULTGATEWAY:{key:"NET",id:10},IPADDRESS_EMPTY_OR_CONTAIN_PRIMARYDNS:{key:"NET",id:11},IPADDRESS_EMPTY_OR_CONTAIN_SECONDARYDNS:{key:"NET",id:12},IPADDRESS_EMPTY_OR_CONTAIN_PRIMARYWINS:{key:"NET",id:13},IPADDRESS_EMPTY_OR_CONTAIN_SECONDARYWINS:{key:"NET",id:14},IPADDRESS_CHANGE_REBOOT_CONFIRMATION:{key:"NET",id:15}};
$(document).ready(function(){NET.loadNetworkAdapterCombo();window.setTimeout(function(){$(".ipv4mask").ipInitialize();
NET.loadPage(0);NET.addValidatorRules();},100);});$(".ipv4mask").bind("validateIpAddress",function(){NET.validateIpAddress($(this));
});$(".ipv4mask").bind("valuechanged",function(){NET.enableSaveAndResetButtons();
});$("select#net_cboNetworkAdapters").change(function(){var d=$(this);if($("#net_btnSave").is(":enabled")){var c=CFG.lookup(NET.msgs.ADAPTER_CHANGE);
var e=$("#net_lblNetworkSettings").text();var a=CFG.lookup(CMN.msgs.DIALOG_OK);var b=CFG.lookup(CMN.msgs.DIALOG_CANCEL);
CMN.showConfirm(c,e,CMN.icons.EXCLAMATION,a,b).then(function(f){if(f.toString()===a){NET.loadData();
d.data("current",d.val());}else{d.val(d.data("current"));}});}else{d.data("current",d.val());
NET.loadData();}});$("#net_rdoDynamic, #net_rdoStatic").on("click",function(){$(this).prop("checked",true);
NET.enableDisableIpInputs();NET.enableSaveAndResetButtons();IPA.resetValidation(NET.isStaticChecked());
return true;});$("#net_btnHelp").on("click",function(){window.open("help/networksettings.htm");
return false;});$("#net_btnSave, #net_btnSaveD").on("click",function(){NET.doSave();
return false;});$("#net_btnRefresh, #net_btnReset").on("click",function(){$("#net_cboNetworkAdapters").focus();
var a=$("#net_btnSave").is(":disabled")?CMN.msgs.REFRESHING:CMN.msgs.RESETTING;CFG.performFunction(NET.loadPage,CFG.getCaption(a));
return false;});NET.doSave=function(){if($("#net_btnSave").is(":disabled")){return;
}if(!$("#frmNetworkSettings").valid()){CFG.showInvalid();return;}CMN.showBusy(CFG.getCaption(CMN.msgs.SAVING));
CFG.timeoutId=window.setTimeout(function(){try{NET.info.oldIpAddress=NET.json.ipaddress;
NET.info.newIpAddress=$("#net_txtIPAddress").val();if(NET.info.oldIpAddress!==NET.info.newIpAddress){if(NET.isExistingIpAddress()){NET.showExistingIpAddressDialog(NET.info.newIpAddress);
return;}}NET.info.isNewIpForLogin=(NET.isLoginDhcp()||(NET.isLoginIp()&&NET.info.oldIpAddress!==NET.info.newIpAddress));
var b=NET.json.isdhcp;NET.info.isChangedToDynamic=(b&&$("#net_rdoDynamic").is(":checked"));
NET.info.isChangedToStatic=(!b&&!$("#net_rdoDynamic").is(":checked"));NET.savePage(true);
CFG.timeoutId=window.setTimeout(function(){CMN.hideBusy();if(NET.info.oldIpAddress!==NET.info.newIpAddress||NET.info.isChangedToDynamic||NET.info.isChangedToStatic){NET.confirmReboot();
}},2000);}catch(a){CFG.handleError(a);return;}},500);};NET.confirmReboot=function(){var d=$("#net_lblNetworkSettings").text();
var c=CFG.lookup(NET.msgs.IPADDRESS_CHANGE_REBOOT_CONFIRMATION);var a=CFG.lookup(CMN.msgs.DIALOG_YES);
var b=CFG.lookup(CMN.msgs.DIALOG_NO);NET.info.showConfirmTime=CMN.dateToMilliseconds();
CMN.showConfirm(c,d,CMN.icons.ASTERISK,a,b).then(function(e){if(e.toString()===a){CFG.doReboot();
}else{NET.reconnect();}});};NET.reconnect=function(){if(NET.info.isNewIpForLogin){CMN.showBusy(String.format(CFG.lookup(NET.msgs.ATTEMPTING_RECONNECT),NET.info.newIpAddress));
CFG.timeoutId=window.setTimeout(function(){if(MOCK.isMockMode()){CMN.hideBusy();}else{CMN.setCookie(document,"key",null,-1);
CMN.setCookie(document,"selectedtab",null,-1);NET.isReconnected=false;NET.attemptReconnect(1);
}},NET.getWaitTime(12000));}else{var b=$("#net_lblStatic").text();var a=$("#net_lblDynamic").text();
if(NET.info.isChangedToDynamic){CMN.showBusy(String.format(CFG.lookup(NET.msgs.CONN_CHANGING_FROM),b,a));
CFG.timeoutId=window.setTimeout(function(){NET.loadPage(10);},NET.getWaitTime(21000));
}else{if(NET.info.isChangedToStatic&&NET.info.oldIpAddress===NET.info.newIpAddress){CMN.showBusy(String.format(CFG.lookup(NET.msgs.CONN_CHANGING_FROM),a,b));
CFG.timeoutId=window.setTimeout(function(){NET.isExistingIpAddress(5);NET.loadPage(10);
},NET.getWaitTime(2000));}else{CMN.showBusy(CFG.lookup(NET.msgs.CHANGES_TO_TAKE_EFFECT));
CFG.timeoutId=window.setTimeout(function(){NET.isExistingIpAddress(5);NET.loadPage(10);
},NET.getWaitTime(13000));}}}};NET.getWaitTime=function(b){var a=b-(CMN.dateToMilliseconds()-NET.info.showConfirmTime);
if(a<500){a=500;}return a;};NET.attemptReconnect=function(c){if(!c){c=1;}var d=document.location.port===""?"":":"+document.location.port;
var e=document.location.protocol+"//"+NET.info.newIpAddress+d;var a=e+"/themes/base/images/ping.png"+CMN.uniqueQueryString();
var b=new window.Image();b.onload=function(){CFG.clearTimeout();NET.isReconnected=true;
jQuery.unblockUI();window.location.href=e+"/loading.htm";return false;};b.onabort=function(){CFG.clearTimeout();
jQuery.unblockUI();return false;};b.onerror=function(){CFG.clearTimeout();if(!NET.isReconnected){if(c<3){NET.attemptReconnect(++c);
}else{var f=String.format(CFG.lookup(NET.msgs.COULD_NOT_RECONNECT),NET.info.newIpAddress,e);
jQuery.unblockUI({onUnblock:function(){CMN.showDialog(f);}});}}return false;};b.src=a;
};NET.enableSaveAndResetButtons=function(){$("#net_btnSave").prop("disabled",false);
$("#net_btnRefresh").addClass("hidden");$("#net_btnReset").removeClass("hidden");
};NET.disableSaveAndResetButtons=function(){$("#net_btnSave").prop("disabled",true);
$("#net_btnReset").addClass("hidden");$("#net_btnRefresh").removeClass("hidden");
};NET.isLoginIp=function(){return NET.json.ipaddress===location.hostname;};NET.isLoginDhcp=function(){return NET.json.isdhcp&&NET.json.machinename.toUpperCase()===location.hostname.toUpperCase();
};NET.isStaticChecked=function(){return($("#net_rdoStatic").is(":checked"));};NET.loadNetworkAdapterCombo=function(){var a="/services/network/adapterinfo";
$.ajax({type:"GET",url:a,dataType:"json",async:false,success:function(b){NET.loadNetworkAdapterComboFromData(b);
},error:function(b){CFG.handleError(b);}});};NET.loadNetworkAdapterComboFromData=function(a){var c=$("#net_cboNetworkAdapters");
for(var b in a){c.append('<option value="'+a[b].id+'">'+a[b].alias+"</option>");}c.data("current",c.val());
};NET.loadPage=function(a){if(typeof a==="number"){if(a>0){CFG.timeoutId=window.setTimeout(function(){CFG.performFunction(NET.loadPage,CFG.getCaption(CMN.msgs.LOADING));
},a);}else{CFG.performFunction(NET.loadPage,CFG.getCaption(CMN.msgs.LOADING));}return;
}$.ajax({type:"GET",url:"/services/network/networksettings?lang="+CFG.getLanguage(),dataType:"xml",cache:false,async:false,success:function(b){NET.loadPageFromXml(b);
},error:function(b){CFG.handleError(b);}});NET.loadData();};NET.loadPageFromXml=function(a){NET.xml=a;
CFG.setLabelsAndTitles(a);};NET.loadData=function(){var a=$("select#net_cboNetworkAdapters option:selected").val();
$.ajax({type:"GET",url:"/services/network/networkdata/"+a,dataType:"json",cache:false,async:false,success:function(b){NET.loadPageData(b);
NET.enableDisableIpInputs();NET.disableSaveAndResetButtons();if(NET.$validator){NET.$validator.resetForm();
IPA.resetValidation(NET.isStaticChecked());}NET.makeSecure();NET.setInitialFocus();
},error:function(b){CFG.handleError(b);}});};NET.loadPageData=function(a){NET.json=a;
$("#net_txtMachineName").html(a.machinename);$("#net_txtMACAddress").html(a.macaddress);
if(a.isdhcp===true){$("#net_rdoDynamic").prop("checked",true);$("#net_rdoDynamic").prop("disabled",false);
$("#net_rdoStatic").prop("checked",false);}else{$("#net_rdoDynamic").prop("checked",false);
$("#net_rdoStatic").prop("checked",true);$("#net_rdoDynamic").prop("disabled",(NET.isLoginIp()||NET.isLoginDhcp()));
}$("#net_txtIPAddress").ipAddress(a.ipaddress);$("#net_txtSubnetMask").ipAddress(a.subnetmask);
$("#net_txtDefaultGateway").ipAddress(a.defaultgateway);$("#net_txtPrimaryDNS").ipAddress(a.primarydns);
$("#net_txtSecondaryDNS").ipAddress(a.secondarydns);$("#net_txtPrimaryWINS").ipAddress(a.primarywins);
$("#net_txtSecondaryWINS").ipAddress(a.secondarywins);};NET.savePage=function(a){var b=NET.getJsonFromPage();
$.ajax({type:"PUT",url:"/services/network/networkdata",dataType:"json",headers:{"x-auth-token":localStorage.accessToken,"Content-Type":"application/json"},global:false,async:a||false,data:JSON.stringify(b),complete:function(c){if(c.status===200){NET.json=b;
}},error:function(c){CFG.handleError(c);}});};NET.getJsonFromPage=function(){var a=NET.json;
a.adapterid=$("select#net_cboNetworkAdapters option:selected").val();a.macaddress=$("#net_txtMACAddress").html();
a.isdhcp=$("#net_rdoDynamic").is(":checked");a.ipaddress=$("#net_txtIPAddress").val();
a.subnetmask=$("#net_txtSubnetMask").val();a.defaultgateway=$("#net_txtDefaultGateway").val();
a.primarydns=$("#net_txtPrimaryDNS").val();a.secondarydns=$("#net_txtSecondaryDNS").val();
a.primarywins=$("#net_txtPrimaryWINS").val();a.secondarywins=$("#net_txtSecondaryWINS").val();
return a;};NET.setInitialFocus=function(){$("#net_cboNetworkAdapters").focus();};
NET.showExistingIpAddressDialog=function(a){var b="<div class='img_exclamation'></div>";
b+="<div id='invalid_text'>The <i>"+CFG.getCurrentTabName();b+="</i> cannot be saved because the specified <b>IP Address</b>: <i>'";
b+=((a)||$("#net_txtIPAddress").ipAddress())+"'</i> already exists on this network.</div>";
CMN.showDialog(b);};NET.isExistingIpAddress=function(a){var c="/services/network/isexisting/"+NET.info.newIpAddress;
if(a){c+="/"+a;}var b=CMN.getJson(c);return b.isexisting;};NET.isCurrentIpAddress=function(b){var a=$("select#net_cboNetworkAdapters option:selected").val();
var d="/services/network/iscurrentipaddress/"+a+"/"+b;var c=CMN.getJson(d);return c.iscurrentipaddress;
};NET.enableDisableIpInputs=function(){if(NET.isStaticChecked()){$("input.ip_octet").prop("disabled",false);
}else{$("input.ip_octet").prop("disabled",true);}};NET.makeSecure=function(){var a=!CMN.isAdminLevel();
$("#net_rdoDynamic, #net_rdoStatic").prop("disabled",a||(NET.isStaticChecked()&&(NET.isLoginIp()||NET.isLoginDhcp())));
$("input.ip_octet").prop("disabled",a||$("#net_rdoDynamic").is(":checked"));};NET.$container=$("#frmNetworkSettings div.errcontainer");
NET.$validator=$("#frmNetworkSettings").validate({debug:true,onsubmit:false,errorClass:"invalid",validClass:"valid",errorContainer:NET.$container,errorLabelContainer:$("ol",NET.$container),wrapper:"li",ignore:".ip_octet"});
NET.addValidatorRules=function(){var b=CFG.lookup(NET.msgs.IPADDRESS_EMPTY_OR_CONTAIN_DEFAULTGATEWAY);
var c=CFG.lookup(NET.msgs.IPADDRESS_MUST_CONTAIN_SUBNETMASK);var d=CFG.lookup(NET.msgs.IPADDRESS_MUST_CONTAIN_IPADDRESS);
var a=$("#net_txtIPAddress");a.rules("remove");a.rules("add",{required:{depends:function(){return NET.isStaticChecked();
}},validip3:true,messages:{required:d,validip3:d}});a=$("#net_txtSubnetMask");a.rules("remove");
a.rules("add",{required:{depends:function(){return NET.isStaticChecked();}},validip2:true,messages:{required:c,validip2:c}});
a=$("#net_txtDefaultGateway");a.rules("remove");a.rules("add",{required:false,validip1:true,messages:{validip1:b}});
};NET.validateIpAddress=function(a){switch(a[0].id){case"net_txtIPAddress":a.ipIsNotBlank();
a.ipIsValid(1);break;case"net_txtSubnetMask":a.ipIsNotBlank();a.ipIsValid(2);break;
case"net_txtDefaultGateway":a.ipIsValid(1);break;}NET.$validator.element(a);};