var CFG=window.CFG;var CMN=window.CMN;var SEC=window.SEC;var MOCK=window.MOCK;$("head").append('<link rel="stylesheet" type="text/css" href="grid/slick.grid.css">');
$("head").append('<link rel="stylesheet" type="text/css" href="grid/slick-default-theme.css">');
$("head").append('<link rel="stylesheet" type="text/css" href="themes/tucson/securitygrid.css">');
CMN.loadScript("grid/lib/jquery.event.drag-2.2.js",true,{});CMN.loadScript("grid/slick.core.js",true,{});
CMN.loadScript("grid/slick.grid.js",true,{});CMN.loadScript("grid/slick.dataview.js",true,{});
CMN.loadScript("grid/plugins/slick.rowselectionmodel.js",true,{});CMN.loadScript("grid/slick.groupitemmetadataprovider.js",true,{});
CMN.loadScript("grid/slick.formatters.js",true,{});CMN.loadScript("grid/plugins/slick.cellrangedecorator.js",true,{});
CMN.loadScript("grid/plugins/slick.cellrangeselector.js",true,{});SEC.grid=null;SEC.dataview=null;
SEC.notDeletedRowsFilter=null;SEC.isSelectingRowsOfGroup=false;SEC.loadSecurityGrid=(function(){try{SEC.json=CMN.getJson("/services/network/userssessions");
if(!SEC.grid){SEC.intializeGrid(SEC.json);}else{SEC.dataview.beginUpdate();SEC.dataview.setItems(SEC.json,"id");
SEC.dataview.setFilter(SEC.notDeletedRowsFilter);SEC.dataview.reSort();SEC.dataview.endUpdate();
}}catch(a){CFG.handleError(a);}});SEC.intializeGrid=function(c){function a(m,j,n,k,l){if(!k&&!l){return"";
}return n===1?'<img src="grid/images/tick.png">':"";}function d(m,j,n,k,l){if(n===null||!k&&!l){return"";
}return moment(CMN.millisecondsToDate(n)).format(SEC.DateTimeFormat);}function i(m,j,n,k,l){return(!k&&!l)?"":SEC.UserLevels[n].Value;
}var h={enableCellNavigation:true,enableColumnReorder:false,rowHeight:23,syncColumnCellResize:true};
var b=[{id:"sec_colUsername",name:"Username",field:"username",sortable:true,width:84,cssClass:"cell-username"},{id:"sec_colUserLevel",name:"User Level",field:"userlevel",sortable:true,width:72,formatter:i},{id:"sec_colDateCreated",name:"Date created",field:"datecreated",sortable:true,width:134,formatter:d},{id:"sec_colDateModified",name:"Date modified",field:"datemodified",sortable:true,width:134,formatter:d},{id:"sec_colEnabled",name:"Enabled",field:"enabled",sortable:true,width:55,cssClass:"cell-checkmark",formatter:a},{id:"sec_colIpAddress",name:"IP Address",field:"ipaddress",sortable:true,width:100},{id:"sec_colLastAccessed",name:"Last Accessed",field:"lastaccessed",sortable:true,width:134,formatter:d}];
var g=new Slick.Data.GroupItemMetadataProvider();SEC.notDeletedRowsFilter=function(j){return j.deleted===0;
};SEC.dataview=new Slick.Data.DataView({inlineFilters:true,groupItemMetadataProvider:g});
SEC.dataview.beginUpdate();SEC.dataview.setItems(c,"id");SEC.dataview.setFilter(SEC.notDeletedRowsFilter);
SEC.dataview.endUpdate();var e=function(k,l){var j=function(m,n){return m[k]>n[k]?1:m[k]<n[k]?-1:0;
};SEC.dataview.sort(j,l);};SEC.grid=new Slick.Grid("#secGrid",SEC.dataview,b,h);SEC.grid.setSortColumn("sec_colUsername",true);
SEC.grid.registerPlugin(g);SEC.grid.setSelectionModel(new Slick.RowSelectionModel());
SEC.dataview.syncGridSelection(SEC.grid);SEC.dataview.onRowsChanged.subscribe(function(k,j){SEC.grid.invalidateRows(j.rows);
SEC.grid.render();});SEC.dataview.onRowCountChanged.subscribe(function(){SEC.grid.updateRowCount();
SEC.grid.render();});SEC.grid.onSort.subscribe(function(k,j){e(j.sortCol.field,j.sortAsc);
});SEC.grid.onSelectedRowsChanged.subscribe(function(j){SEC.selectGroupRows();j.stopImmediatePropagation();
});e("username",true);f();function f(){SEC.dataview.setGrouping({getter:"username",formatter:function(j){return j.value+"  <span style='color:green'>("+j.count+" items)</span>";
},collapsed:false,aggregateCollapsed:true,displayTotalsRow:false});}};SEC.getSelectedRownum=function(){var a=SEC.grid.getSelectedRows();
return(a)?a[0]:1;};SEC.getRownumByUsername=function(c){if(!c){return null;}var a=SEC.dataview.getItems();
var d=c.toLowerCase();for(var b=0;b<a.length;b++){if(d===a[b].username.toLowerCase()){return SEC.dataview.getRowById(a[b].id);
}}return null;};SEC.getRowCount=function(){return SEC.grid.getDataLength();};SEC.getGroupByUsername=function(c){var a=SEC.dataview.getGroups();
for(var b=0;b<a.length;b++){if(a[b].groupingKey===c){return a[b];}}return null;};
SEC.selectGroupRows=function(){if(SEC.isSelectingRowsOfGroup){return;}var b=SEC.grid.getSelectedRows();
var a=null;if(b&&b.length){a=SEC.grid.getDataItem(b[0]);if(!a.__group){SEC.setSelectedRowsOfGroup(SEC.getGroupByUsername(a.username));
}}SEC.loadFormFromDataItem(a);};SEC.setSelectedRow=function(b){var a=b;if(typeof b==="string"){a=SEC.dataview.getRowById(b);
}if((!a)||a<0){SEC.grid.setSelectedRows([]);}else{SEC.isSelectingRowsOfGroup=true;
SEC.grid.setSelectedRows([a]);SEC.isSelectingRowsOfGroup=false;}};SEC.setSelectedRowsOfGroup=function(b){if(!b||!b.rows){return;
}var a=[];for(var c=0;c<b.rows.length;c++){a.push(b.rows[c].id);}SEC.isSelectingRowsOfGroup=true;
SEC.grid.setSelectedRows(SEC.dataview.mapIdsToRows(a));SEC.isSelectingRowsOfGroup=false;
};$("#sec_btnExpandAll").on("click",function(){SEC.dataview.expandAllGroups();return false;
});$("#sec_btnCollapAll").on("click",function(){SEC.grid.setSelectedRows([]);SEC.dataview.collapseAllGroups();
return false;});