var CFG=window.CFG;var CMN=window.CMN;var MOCK=window.MOCK;var SEC=SEC||{};SEC.xml=null;
SEC.json=null;SEC.UserLevels=[];SEC.DateTimeFormat="";SEC.msgs={INVALID_USERNAME_PASSWORD:{key:"SEC",id:1},PASSWORD_MIN_LEN:{key:"SEC",id:2},PASSWORD_REQD:{key:"SEC",id:3},PASSWORDS_MUST_MATCH:{key:"SEC",id:4},USERNAME_MIN_LEN:{key:"SEC",id:5},USERNAME_REQD:{key:"SEC",id:6},ADD_USER_MODE:{key:"SEC",id:7},UPD_USER_MODE:{key:"SEC",id:8},REM_USER_MODE:{key:"SEC",id:9}};
var EMPTYPassword="@@@@@@@@";var DefaultPassword="        ";var originalValues=[];
$(document).ready(function(){CFG.performFunction(function(){SEC.loadPage();var a=SEC.getRownumByUsername(SEC.getUsername());
SEC.grid.setSelectedRows([a]);SEC.grid.scrollRowToTop([a-1]);},CFG.getCaption(CMN.msgs.LOADING));
});$("#sec_btnHelp").on("click",function(){window.open("help/securitysettings.htm");
return false;});$("#sec_txtPassword, #sec_txtPasswrd2").focus(function(){if(!originalValues[this.id]){originalValues[this.id]=$(this).val();
}if($(this).val()===originalValues[this.id]){$(this).val(EMPTY);}});$("#sec_txtPassword, #sec_txtPasswrd2").blur(function(){if($(this).val()===EMPTY){$(this).val(originalValues[this.id]);
if(this.id==="sec_txtPasswrd2"){$("#frmSecuritySettings").valid();}}});$("#sec_txtUsername").contextDelete({cut:function(a){SEC.enableSaveAndResetButtons(a);
},paste:function(a){SEC.enableSaveAndResetButtons(a);},contextDelete:function(a){SEC.enableSaveAndResetButtons(a);
}});$("#sec_txtPassword").contextDelete({cut:function(a){SEC.enableSaveAndResetButtons(a);
},paste:function(a){SEC.enableSaveAndResetButtons(a);},contextDelete:function(a){SEC.enableSaveAndResetButtons(a);
}});$("#sec_txtUsername, #sec_txtPassword, #sec_txtPasswrd2").bind("keypress keydown",function(a){if(CMN.processKey(a,"alphanumeric")){SEC.enableSaveAndResetButtons(a);
}});$("#sec_txtUsername, #sec_txtPassword, #sec_txtPasswrd2").bind("cut paste",function(a){if(CMN.processCutPaste(a,"alphanumeric")){SEC.enableSaveAndResetButtons(a);
}});$("#sec_chkNoPwdReqd").on("click",function(){var a=$(this).is(":checked");$("#sec_txtPassword, #sec_txtPasswrd2").prop("disabled",a).val(a?String.empty:DefaultPassword);
SEC.enableSaveAndResetButtons(this);return true;});$("select#sec_cboUserLevel").change(function(){SEC.enableSaveAndResetButtons(this);
});$("#sec_btnAddUser").on("click",function(){SEC.loadFormFromDataItem();SEC.grid.setSelectedRows({});
SEC.grid.setActiveCell({});$("#sec_txtUsername").prop("disabled",false);$("#sec_txtUsername").focus().select();
return true;});$("#sec_btnRemUser").on("click",function(){SEC.showEditMode(SEC.msgs.REM_USER_MODE);
$("#sec_btnRemUser").prop("disabled",true);$("#sec_btnAddUser").prop("disabled",true);
$("#sec_txtUsername").prop("disabled",true);$("#sec_chkNoPwdReqd").prop("disabled",true);
$("#sec_txtPassword").prop("disabled",true);$("#sec_txtPasswrd2").prop("disabled",true);
$("#sec_cboUserLevel").prop("disabled",true);$("#sec_btnSave").prop("disabled",false);
$("#sec_chkLoginEnabled").prop("disabled",true);$("#sec_chkDeleted").prop("checked",true);
$("#sec_txtUsername").addClass("sec_to_delete");$("#sec_txtPassword").addClass("sec_to_delete");
$("#sec_txtPasswrd2").addClass("sec_to_delete");$("#sec_cboUserLevel").addClass("sec_to_delete");
$("#sec_txtDateCreated").addClass("sec_to_delete");$("#sec_txtDateModified").addClass("sec_to_delete");
$(".selected.slick-cell").addClass("sec_to_delete");$("#sec_btnRefresh").addClass("hidden");
$("#sec_btnReset").removeClass("hidden");$("#sec_btnSave").focus();return true;});
$("#sec_chkLoginEnabled").on("click",function(){SEC.enableDisableInputs();SEC.enableSaveAndResetButtons(this);
SEC.resetValidation($(this).is(":checked"));return true;});$("#sec_btnSave").on("click",function(){if($("#sec_chkDeleted").is(":checked")||$("#frmSecuritySettings").valid()){CFG.performFunction(SEC.savePage,CFG.getCaption(CMN.msgs.SAVING));
}else{CFG.showInvalid();}return false;});$("#sec_btnRefresh, #sec_btnReset").on("click",function(){var a=CFG.getCaption($("#sec_btnSave").is(":disabled")?CMN.msgs.REFRESHING:CMN.msgs.RESETTING);
CFG.performFunction(SEC.loadPage,a);return false;});SEC.loadPage=function(){var a="/services/network/securitysettings?lang="+CFG.getLanguage();
$.ajax({type:"GET",url:a,dataType:"xml",async:false,cache:false,success:function(b){SEC.loadPageFromXml(b);
},error:function(b){CFG.handleError(b);}});};SEC.loadPageFromXml=function(e){SEC.DateTimeFormat=$(e).find("SecuritySettings").find("DateTimeFormat").text();
SEC.loadUserLevelsComboFromXml(e);SEC.loadSecurityGrid();var d=SEC.getUsername()||CMN.getUsername();
var b=SEC.getRownumByUsername(d);SEC.grid.setSelectedRows([b]);var c=SEC.grid.getSelectedRows();
if(c.length){var a=SEC.grid.getDataItem(c[0]);SEC.loadFormFromDataItem(a);}SEC.enableDisableInputs();
SEC.disableSaveAndResetButtons();CFG.setLabelsAndTitles(e);$("#sec_chkNoPwdReqd").prop("title",$("#sec_lblNoPasswordReqd").prop("title"));
$("#sec_chkLoginEnabled").prop("title",$("#sec_lblLoginEnabled").prop("title"));SEC.addValidatorRules();
SEC.resetValidation();SEC.makeSecure();SEC.xml=e;};SEC.savePage=function(){var b=false;
var e=SEC.getSelectedRownum();var d=SEC.getRowCount();var a=SEC.getJsonFromPage();
$.ajax({type:"PUT",url:"/services/network/securitydata",dataType:"json",headers:{"x-auth-token":localStorage.accessToken,"Content-Type":"application/json"},cache:false,global:false,async:false,data:JSON.stringify(a),complete:function(f){if(f.status===200){SEC.loadPage();
}},error:function(f){if(f.status!==200){b=true;CFG.handleError(f);}}});if(!b){var c=SEC.getRowCount();
if(c<d){e-=(d-c);}else{e=SEC.getRownumByUsername(a.username);}SEC.grid.setSelectedRows([e]);
SEC.grid.scrollRowIntoView(SEC.grid.getSelectedRows()[0],true);}};SEC.getJsonFromPage=function(){var a=$("#sec_chkNoPwdReqd").is(":checked")?EMPTYPassword:CMN.trim($("#sec_txtPassword").val());
var b={username:SEC.getUsername(),password:a,userlevel:parseInt($("#sec_cboUserLevel").val(),10),enabled:SEC.isUserAllowedLogin()?1:0,deleted:$("#sec_chkDeleted").is(":checked")?1:0};
return b;};SEC.getUsername=function(){return CMN.toTitleCase(CMN.trim($("#sec_txtUsername").val()));
};SEC.loadFormFromDataItem=function(b){if(!b||b.__group){$("#sec_txtUsername").val(EMPTY);
$("#sec_chkLoginEnabled").prop("checked",true);$("#sec_chkDeleted").prop("checked",false);
$("#sec_txtDateCreated").val(EMPTY);$("#sec_txtDateModified").val(EMPTY);$("#sec_txtPassword").val(EMPTY);
$("#sec_txtPasswrd2").val(EMPTY);$("#sec_btnRefresh").addClass("hidden");$("#sec_btnReset").removeClass("hidden");
$("#sec_cboUserLevel").prop("selectedIndex",1);$("#sec_btnAddUser").prop("disabled",true);
$("#sec_btnRemUser").prop("disabled",true);SEC.showEditMode(SEC.msgs.ADD_USER_MODE);
}else{$("#sec_txtUsername").val(b.username);$("#sec_chkLoginEnabled").prop("checked",(b.enabled===1));
$("#sec_chkDeleted").prop("checked",(b.deleted===1));$("#sec_txtDateCreated").val(moment(CMN.millisecondsToDate(b.datecreated)).format(SEC.DateTimeFormat));
$("#sec_txtDateModified").val(moment(CMN.millisecondsToDate(b.datemodified)).format(SEC.DateTimeFormat));
$("#sec_txtPassword").val(DefaultPassword);$("#sec_txtPasswrd2").val(DefaultPassword);
$("#sec_btnRefresh").removeClass("hidden");$("#sec_btnReset").addClass("hidden");
$("#sec_cboUserLevel").prop("selectedIndex",parseInt(b.userlevel,10));var a=!CMN.isAdminLevel();
$("#sec_btnAddUser").prop("disabled",a);$("#sec_btnRemUser").prop("disabled",a||b.username==="Admin");
SEC.showEditMode(SEC.msgs.UPD_USER_MODE);}$("#sec_btnSave").prop("disabled",true);
$("#sec_chkNoPwdReqd").prop("checked",false);$(".sec_to_delete").removeClass("sec_to_delete");
SEC.enableDisableInputs();if(SEC.$validator){SEC.$validator.resetForm();}};SEC.loadUserLevelsComboFromXml=function(c){var b=$("#sec_cboUserLevel");
b.empty();var a=$(c).find("UserLevels").children();$(a).each(function(){var d=$(this).attr("Id");
var e=$(this).attr("lbl");b.append($("<option/>").attr("value",d).text(e));SEC.UserLevels.push({Key:d,Value:e});
});};SEC.showEditMode=function(a){$("#sec_lblEditMode").text(CMN.isAdminLevel()||(a.id===8&&$("#sec_txtUsername").val()===CMN.getUsername())?"["+CFG.lookup(a)+"]":"");
};SEC.enableDisableInputs=function(){var b=CMN.isAdminLevel();var a=$("#sec_btnAddUser").prop("disabled");
var c=$("#sec_txtUsername").val()==="Admin";$("#sec_txtUsername").prop("disabled",!b||!a);
if(b||!a&&SEC.isUserAllowedLogin()){$("#sec_txtPassword, #sec_txtPasswrd2").prop("disabled",$("#sec_chkNoPwdReqd").is(":checked"));
$("#sec_chkNoPwdReqd").prop("disabled",false);$("#sec_cboUserLevel").prop("disabled",c);
}else{$("#sec_chkNoPwdReqd, #sec_cboUserLevel").prop("disabled",true);$("#sec_txtPassword, #sec_txtPasswrd2").prop("disabled",$("#sec_txtUsername").val()!==CMN.getUsername());
}$("#sec_chkLoginEnabled").prop("disabled",!b||c);};SEC.makeSecure=function(){};SEC.enableSaveAndResetButtons=function(a){$("#sec_btnSave").prop("disabled",false);
$("#sec_btnRefresh").addClass("hidden");$("#sec_btnReset").removeClass("hidden");
CMN.validateMe(a);};SEC.disableSaveAndResetButtons=function(){$("#sec_btnSave").prop("disabled",true);
$("#sec_btnReset").addClass("hidden");$("#sec_btnRefresh").removeClass("hidden");
};SEC.isUserAllowedLogin=function(){return($("#sec_chkLoginEnabled").is(":checked"));
};SEC.setInitialFocus=function(){$("#secGrid").focus().select();};SEC.$container=$("#frmSecuritySettings div.errcontainer");
SEC.$validator=$("#frmSecuritySettings").validate({errorContainer:SEC.$container,errorLabelContainer:$("ol",SEC.$container),errorClass:"invalid",validClass:"valid",wrapper:"li"});
SEC.addValidatorRules=function(){var a=$("#sec_txtUsername");a.rules("remove");a.rules("add",{required:{},minlength:{param:3},messages:{required:CFG.lookup(SEC.msgs.USERNAME_REQD),minlength:String.format(CFG.lookup(SEC.msgs.USERNAME_MIN_LEN),3)}});
a=$("#sec_txtPassword");a.rules("remove");a.rules("add",{});a=$("#sec_txtPasswrd2");
a.rules("remove");a.rules("add",{equalTo:{depends:function(){return SEC.isUserAllowedLogin()&&!CMN.isReallyEmpty($("#sec_txtPassword"));
},param:"#sec_txtPassword"},messages:{equalTo:CFG.lookup(SEC.msgs.PASSWORDS_MUST_MATCH)}});
};SEC.resetValidation=function(a){if(a){$("#sec_txtUsername, #sec_txtPasswrd2").valid();
}else{SEC.$validator.resetForm();$("#sec_txtUsername, #sec_txtPasswrd2").removeClass("invalid");
}};