var CMN=window.CMN;var CFG=window.CFG;var MOCK=window.MOCK;var LGN={};LGN.xml=null;
LGN.msgs={PASSWORD_MIN_LEN:{key:"LGN",id:1},PASSWORD_REQD:{key:"LGN",id:2},USERNAME_MIN_LEN:{key:"LGN",id:3},USERNAME_REQD:{key:"LGN",id:4}};
CMN.hideBusy();$("#lgn_txtUsername").bind("keypress",function(a){if(a.keyCode===13||a.charCode===13){if($(this).val()!==EMPTY){a.preventDefault();
return LGN.login();}}else{if(CMN.processKey(a,"alphanumeric")){LGN.enableLoginAndResetButtons(a);
}}return true;});$("#lgn_txtPassword").bind("keypress",function(a){if(a.keyCode===13||a.charCode===13){a.preventDefault();
return LGN.login();}return true;});$("#lgn_txtUsername").bind("cut paste",function(a){LGN.enableLoginAndResetButtons(a);
});$("#lgn_txtUsername").contextDelete({cut:function(a){LGN.enableLoginAndResetButtons(a);
},paste:function(a){LGN.enableLoginAndResetButtons(a);},contextDelete:function(a){LGN.enableLoginAndResetButtons(a);
}});$("#lgn_btnLogin").on("click",function(){if($("#lgn_txtUsername").val()===EMPTY){CFG.showInvalid();
}else{return LGN.login();}return false;});$("#lgn_btnReset").on("click",function(){LGN.loadPage();
return false;});$("#lgn_btnHelp").on("click",function(){window.open("help/login.htm");
return false;});LGN.enableLoginAndResetButtons=function(a){if(a){$("#lgn_btnLogin").prop("disabled",false);
}};LGN.loadPage=function(){var a="/services/network/login?lang="+CFG.getLanguage();
$.ajax({type:"GET",url:a,dataType:"xml",async:false,cache:false,success:function(b){LGN.loadPageFromData(b);
},error:function(b){CFG.handleError(b);}});};LGN.loadPageFromData=function(d){CFG.setLabelsAndTitles(d);
var a=CMN.getRemember()||false;var b=CMN.getTimeout()||300;var c=CMN.getUsername();
if(a){$("#lgn_txtUsername").val(c);$("#lgn_btnLogin").prop("disabled",false);}else{$("#lgn_txtUsername").val("");
$("#lgn_btnLogin").prop("disabled",true);}$("#lgn_txtPassword").val("");$("#lgn_chkRememberMe").prop("checked",a);
CFG.idle.max(b);LGN.xml=d;LGN.setFocus();};LGN.setFocus=function(){var a=$("#lgn_txtUsername");
if(a.val().length!==0){a=$("#lgn_txtPassword");}a.focus().select();};LGN.login=function(){var a=LGN.getJsonFromPage();
$.ajax({type:"PUT",url:"/services/network/login",dataType:"json",headers:{"x-auth-token":localStorage.accessToken,"Content-Type":"application/json"},global:false,async:false,cache:false,data:JSON.stringify(a),complete:function(b){if(b.status===200){$("#lgn_txtPassword").val("");
CFG.hideLogin();}},error:function(b){CFG.handleError(b);LGN.setFocus();return false;
}});};LGN.getJsonFromPage=function(){var a={username:$("#lgn_txtUsername").val(),password:$("#lgn_txtPassword").val(),remember:$("#lgn_chkRememberMe").prop("checked")};
return a;};LGN.isValidPassword=function(a){return a===EMPTY||a===0||(a>9&&a<=99999);
};LGN.$container=$("#frmLogin div.errcontainer");LGN.$validator=$("#frmLogin").validate({debug:true,errorContainer:LGN.$container,errorLabelContainer:$("ol",LGN.$container),errorClass:"invalid",validClass:"valid",wrapper:"li"});
LGN.addValidatorRules=function(){var a=$("#lgn_txtUsername");a.rules("remove");a.rules("add",{minlength:{param:4},messages:{required:CFG.lookup(LGN.msgs.USERNAME_REQD),minlength:CFG.lookup(LGN.msgs.USERNAME_MIN_LEN)}});
a=$("#lgn_txtPassword");a.rules("remove");a.rules("add",{minlength:{param:6},messages:{required:CFG.lookup(LGN.msgs.PASSWORD_REQD),minlength:CFG.lookup(LGN.msgs.PASSWORD_MIN_LEN)}});
};LGN.loadPage();