if(typeof jQuery==="undefined"){throw"jQuery.js must be loaded before this module.";
}if(typeof jQuery.blockUI==="undefined"){throw"jQuery.blockUI.js must be loaded before this module.";
}var EMPTY="";var CMN=CMN||{};CMN.BASE_IMAGE_PATH="themes/base/images/";CMN.TUCSON_IMAGE_PATH="themes/tucson/images/";
CMN.msgs={PLEASE_WAIT:{key:"CMN",id:1},LOADING:{key:"CMN",id:2},SAVING:{key:"CMN",id:3},REFRESHING:{key:"CMN",id:4},RESETTING:{key:"CMN",id:5},DIALOG_OK:{key:"CMN",id:6},DIALOG_CANCEL:{key:"CMN",id:7},DIALOG_YES:{key:"CMN",id:8},DIALOG_NO:{key:"CMN",id:9},DIALOG_RETRY:{key:"CMN",id:10},ERROR:{key:"CMN",id:11},WARNING:{key:"CMN",id:12},MESSAGE:{key:"CMN",id:13},INVALID_DATA_ERROR:{key:"CMN",id:14},INVALID_USERNAME_PASSWORD:{key:"CMN",id:15},LOGIN_DISABLED:{key:"CMN",id:16},CONFIG_ERROR:{key:"CMN",id:17},UNKNOWN_ERROR:{key:"CMN",id:18},DEVICE_NOT_RESPONDING:{key:"CMN",id:19},FEATURE_UNDERCONSTRUCTION:{key:"CMN",id:10},FEATURE_UNAVAILABLE:{key:"CMN",id:21},NETWORK_CONN:{key:"CMN",id:22},CURRENT_USER:{key:"CMN",id:23},REBOOTING:{key:"CMN",id:24}};
CMN.icons={INFORMATION:"information.png",EXCLAMATION:"exclamation.png",QUESTION:"question.png",ASTERISK:"asterisk.png"};
CMN.isIE=function(){return window.detect.parse(navigator.userAgent).browser.family==="IE";
};CMN.getUsername=function(){return CMN.getCookie(document,"username");};CMN.getUserLevel=function(){var a=CMN.getCookie(document,"userlevel");
return(a)?parseInt(a,10):1;};CMN.getRemember=function(){var a=CMN.getCookie(document,"remember");
return(a)?a:false;};CMN.getTimeout=function(){return CMN.getCookie(document,"timeout");
};CMN.isAdminLevel=function(){return CMN.getUserLevel()===0;};CMN.validateMe=function(a){window.setTimeout(function(){return((a.target)?$("#"+a.target.id).valid():true);
},100);};CMN.getDataXml=function(b){var a=b;$(a).children().children().not(function(){return this.tagName==="Data";
}).remove();return CMN.xmlToString(a);};CMN.isXmlEqual=function(b,c){var a=/^<\?xml\s+version\s*=\s*(["'])[^\1]+\1[^?]*\?>/;
return CMN.xmlToString(b).replace(a,"")===CMN.xmlToString(c).replace(a,"");};CMN.xmlToString=function(a){var b;
if(window.ActiveXObject){b=a.xml;}else{b=(new XMLSerializer()).serializeToString(a);
}return b;};CMN.isChecked=function(a){return a.is(":checked")?"true":"false";};CMN.getJson=function(c){var a,b;
$.ajax({type:"GET",url:c,dataType:"json",async:false,success:function(d){b=d;},error:function(d){a=d;
}});if(a){throw new Error(a.responseJSON,a.status);}return b;};CMN.getXml=function(c){var a,b;
$.ajax({type:"GET",url:c,dataType:"xml",async:false,success:function(d){b=d;},error:function(d){a=d;
}});if(a){throw new Error(a.responseText,a.status);}return b;};CMN.copyProps=function(b,c){for(var a in b){if(b.hasOwnProperty(a)){if((a in c)){c[a]=b[a];
}}}};CMN.compare=function(c,d){for(var a in c){if(c.hasOwnProperty(a)){if(!(a in d)){return false;
}else{if((typeof c[a]=="object")&&(typeof d[a]=="object")){if(!CMN.compare(c[a],d[a])){return false;
}}else{if(c[a]!==d[a]){return false;}}}}}for(var b in d){if(d.hasOwnProperty(b)){if(!(b in c)){return false;
}}}return true;};CMN.getDifferences=function(d,e){var a={};for(var b in d){if(d.hasOwnProperty(b)){if(!(b in e)){a[b]=undefined;
}else{if(d[b]!==e[b]){a[b]=e[b];}}}}for(var c in e){if(e.hasOwnProperty(c)){if(!(c in d)){a[c]=e[c];
}}}return a;};CMN.getSelectedText=function(){if(window.getSelection){return window.getSelection();
}else{if(document.getSelection){return document.getSelection();}else{var a=document.selection&&document.selection.createRange();
if(a.text){return a.text;}return false;}}};CMN.toTitleCase=function(a){return a.replace(/\w\S*/g,function(b){return b.charAt(0).toUpperCase()+b.substr(1).toLowerCase();
});};CMN.getFormattedDateTime=function(a){if(!a){a=new Date();}return moment(a).format("MM/DD/YYYY hh:mm:ss A");
};$.fn.getCursorPosition=function(){var a=this.get(0);if(!a){return 0;}if("selectionStart" in a){return a.selectionStart;
}else{if(document.selection){a.focus();var b=document.selection.createRange();var c=document.selection.createRange().text.length;
b.moveStart("character",-a.value.length);return b.text.length-c;}}return 0;};(function(a){a.fn.contextDelete=function(b){var d={obj:a(this),menu:false,paste:false,cut:false,copy:false,set:"",ie:null};
var c=a.extend({contextDelete:function(){},paste:function(){},cut:function(){},copy:function(){},allContext:false},b);
a(window).bind({click:function(){d.menu=false;},keyup:function(){d.menu=false;}});
d.obj.bind({contextmenu:function(){d.menu=true;d.paste=false;d.cut=false;d.copy=false;
d.val=d.obj.val();if(CMN.isIE){d.ie=window.setInterval(function(){d.obj.trigger(a.Event("input"));
if(!d.menu){window.clearInterval(d.ie);}},300);}},paste:function(f){d.paste=true;
if(c.allContext){if(d.menu){c.paste(f);d.menu=false;}}else{c.paste(f);}},cut:function(f){d.cut=true;
if(c.allContext){if(d.menu){c.cut(f);d.menu=false;}}else{c.cut(f);}},copy:function(f){d.copy=true;
if(c.allContext){if(d.menu){c.copy(f);d.menu=false;}}else{c.copy(f);}},input:function(f){if(d.menu&&(!d.paste)&&(!d.cut)&&(!d.copy)){if(d.obj.val().length<d.val.length){c.contextDelete(f);
d.menu=false;}}}});};})(jQuery);CMN.processKey=function(b,c,a){var d=b.keyCode||b.charCode;
if(b.type==="keydown"){if(d===8){return((CMN.getSelectedText())||(b.target.value.length>0&&$(b.target).getCursorPosition()>0));
}else{if(d===46){return((CMN.getSelectedText())||($(b.target).getCursorPosition()<b.target.value.length));
}else{if(d===9||d===27||d===13||d===123||(b.ctrlKey)||(!b.shiftKey&&(d>=35&&d<=39))){return false;
}}}}if(c==="numeric"){if(b.shiftKey||(d<48||d>57)&&(d<96||d>105)){b.preventDefault();
return false;}return true;}else{if(b.type==="keypress"&&c==="alphanumeric"){if(d===8||(d===32&&(a)&&a!=="false")){return true;
}if(d===9||d>=36&&d<=39){return true;}if((b.shiftKey&&(d>=48&&d<=57))||(String.fromCharCode(d).replace(/^[a-zA-Z0-9\-\.]*$/g,"")!=="")&&((b.shiftKey||(d!==189&&d!==190)))){if(d!==13){b.preventDefault();
}return false;}return true;}else{if(b.type==="keypress"&&c==="filepath"){if(String.fromCharCode(d).replace(/^[a-zA-Z0-9\~\!\@\#\$\%\^\&\(\)\_\-\+\=\{\}\[\]\,\.\047 ]+$/g,"")===""){return true;
}else{b.preventDefault();}}}}return false;};CMN.processCutPaste=function(c,d,a){if(c.type==="cut"){return true;
}else{if(c.type==="paste"){var b=window.clipboardData?window.clipboardData.getData("Text"):c.originalEvent.clipboardData.getData("text/plain");
var f=null;if(d==="numeric"){f=/[0-9]*/g;}else{if(d==="alphanumeric"){f=((a)&&a!=="false")?/^[a-zA-Z0-9\-\. ]*$/g:/^[a-zA-Z0-9\-\.]*$/g;
}else{if(d==="filepath"){f=/^[a-zA-Z0-9\~\!\@\#\$\%\^\&\(\)\_\-\+\=\{\}\[\]\,\.\047 ]+$/g;
}}}if((b&&f)?(b.replace(f,"")===""):false){return true;}c.preventDefault();}}return false;
};CMN.getCookie=function(e,d){var g=d+"=";var b=e.cookie.split(";");for(var f=0;f<b.length;
f++){var a=b[f];while(a.charAt(0)===" "){a=a.substring(1,a.length);}if(a.indexOf(g)===0){return window.unescape(a.substring(g.length,a.length));
}}return null;};CMN.setCookie=function(c,a,f,e){var d=new Date();d.setDate(d.getDate()+e);
var b=window.escape(f)+((e===null)?"":"; Expires="+d.toUTCString());c.cookie=a+"="+b;
};CMN.showBusy=function(a){jQuery.blockUI.defaults.css={};jQuery.blockUI.defaults.fadeOut=800;
jQuery.blockUI({message:"<img src='"+CMN.BASE_IMAGE_PATH+"busy.gif'/>&nbsp;&nbsp;"+a,theme:false,ignoreIfBlocked:false,css:{width:"500px",top:"137px",left:($(window).width()-532)/2+"px",padding:"10px",margin:"10px",fontSize:"12pt",textAlign:"center",color:"#000000",border:"3px solid #aaa",backgroundColor:"#ffffff",cursor:"wait"},overlayCSS:{backgroundColor:"#A0A0A0"}});
};CMN.hideBusy=function(){jQuery.unblockUI();};CMN.showDialog=function(b,c,d,a){jQuery.unblockUI();
window.setTimeout(function(){jQuery("<div>").dialog({modal:true,dialogClass:"dialog_style1",autoOpen:true,resizable:true,buttons:{OK:function(){$(this).dialog("close");
}},title:(c)?c:document.title,width:(d)?d:450,height:(a)?a:200,open:function(){$(this).html(b);
},close:function(){$(this).dialog("close");}});},400);};CMN.showConfirm=function(h,i,g,a,b,j,e){var d=$.Deferred();
var c=false;var f=(g)?'<span class="dialog_image"><img src="'+CMN.TUCSON_IMAGE_PATH+g+'"></span>'+h:h;
$("<div></div>").html(f).dialog({modal:true,dialogClass:"dialog_style1",autoOpen:true,buttons:[{text:a,click:function(){c=true;
d.resolve(a);$(this).dialog("close");}},{text:b,click:function(){c=true;d.resolve(b);
$(this).dialog("close");}}],title:(i)?i:document.title,width:(j)?j:450,height:(e)?e:200,close:function(){if(!c){d.resolve("");
}$(this).remove();}});return d.promise();};CMN.openWindow=function(e,c,b,d){if(d){if(!d.closed){d.focus();
d.location.reload();return d;}}var a=window.open(e,c,b);return a;};CMN.loadStyle=function(a){var b=true;
jQuery("link[type='text/css']").each(function(){b=(a!==$(this).attr("href"));return;
});if(b){var c=document.createElement("link");c.rel="stylesheet";c.type="text/css";
c.media="screen";c.href=a;document.getElementsByTagName("head")[0].appendChild(c);
}};CMN.loadScript=function(f,a,b){var d;var c;if($.isFunction(a)){c=a;d=b;}else{d=a;
c=b;}var e=true;jQuery("script[type='text/javascript']").each(function(){e=(f!==$(this).attr("src"));
return e;});if(e){jQuery.ajax({type:"GET",url:f,async:false,dataType:"script",cache:d,success:c});
}else{if(jQuery.isFunction(c)){if(c){c.call(this);}}}};CMN.pause=function(a){a+=new Date().getTime();
while(new Date()<a){}};CMN.getQueryStringByName=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");
var b=new RegExp("[\\?&]"+a+"=([^&#]*)"),c=b.exec(location.search);return c===null?"":decodeURIComponent(c[1].replace(/\+/g," "));
};CMN.millisecondsToDate=function(a){return new Date(parseFloat(a));};CMN.millisecondsUtcToDate=function(b){var a=(new Date()).getTimezoneOffset()*60000;
return new Date(parseFloat(b)+a);};CMN.dateToMilliseconds=function(a){return Date.parse(!a?(new Date()):a);
};CMN.dateToMillisecondsUtc=function(a){if(!a){a=new Date();}return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds());
};CMN.numberWithCommas=function(a){return a.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");
};CMN.fixResponseText=function(a){var b=a.replace("<html","<div");b=b.replace("<html>","</div>");
b=b.replace("<head>","");b=b.replace("<body>","");b=b.replace("<center>","");b=b.replace("</head>","");
b=b.replace("</body>","");b=b.replace("</center>","");b=b.replace("540px;","100%;");
b=b.replace("600px;","100%;");b=b.replace(/auto/g,"0");b=b.replace(/20px/g,"0");b=b.replace(/50px/g,"0");
b=b.replace(/40px/g,"10px");b=b.replace("float: left;","");b=b.replace("background-color: #f0f0f0;","");
b=b.replace("<div style='clear: both;'/>","");b=b.replace("9pt;'>\r","8pt;'>\r");
b=b.replace("11pt;","11pt; margin-right: 45px;");b=b.replace("padding-right: 10px","padding-right: 30px");
b=b.replace("<br/><br/>","<br/>");return b;};CMN.fileExists=function(a){var b=jQuery.ajax({type:"HEAD",url:a,async:false}).status;
return(b===200)?true:false;};CMN.trim=function(a){return a.replace(/^\s+|\s+$/g,"");
};String.format=function(){var c=arguments[0];for(var a=1;a<arguments.length;a++){var b=new RegExp("\\{"+(a-1)+"\\}","gm");
c=c.replace(b,arguments[a]);}return c;};CMN.uniqueQueryString=function(){return"?_="+new Date().getTime();
};CMN.getRandom=function(){return Math.floor(Math.random()*101010101);};CMN.isReallyEmpty=function(a){return(a.val())&&a.val().replace(/^\s+|\s+$/gm,EMPTY)===EMPTY;
};CMN.checkForError=function(){var a=CMN.getCookie(document,"error");if(a){CMN.setCookie(document,"error",null,-1);
CMN.showDialog(a,"PAC Configuration Tool Error");}};CMN.debugLog=function(a){if(typeof window.console!=="undefined"){if(CMN.isIE()){window.console.log(moment().format("hh:mm:ss")+" -- "+a);
}else{window.console.log(a);}}};CMN.cloneXmlDoc=function(c){var a=c.implementation.createDocument(c.namespaceURI,null,null);
var b=a.importNode(c.documentElement,true);a.appendChild(b);return a;};