var CMN=window.CMN;var MOCK=MOCK||{};MOCK.isMockMode=function(){return(!document.domain||document.domain==="localhost"||document.domain==="127.0.0.1");
};MOCK.addLanguagesToXml=function(c,a){var d=CMN.getXml("/services/network/demo/supportedlanguages");
var b=$(d).find("Languages[id='"+a+"']");if((b)){$(c).find("ConfigTool")[0].appendChild(b[0]);
}return c;};MOCK.addValuesToXpressSettingsXml=function(a){var b=CMN.getXml("/services/network/demo/xpresssettings");
$(b).children().children().each(function(){$(a)[0].documentElement.appendChild(this);
});return a;};MOCK.addValuesToAboutInfoXml=function(h){var j=CMN.getXml("/services/network/demo/aboutinfo");
var d=["SerialNumber","Platform","WinCEVersion"];for(var c in d){if(d.hasOwnProperty(c)){var e=d[c];
$(h).find(e).text($(j).find(e).text());}}$(h).find("ModelNumber").text($(j).find("ModelNumber").text());
d=$(h).find("ModelNumberItem");var b;var a;for(a=0;a<d.length;a++){b=$(d)[a].attributes.getNamedItem("Id").value;
$(h).find("ModelNumberItem[Id='"+b+"']").text($(j).find("ModelNumberItem[Id='"+b+"']").text());
}$(h).find("XpsFirmware").text($(j).find("XpsFirmware").text());$(h).find("PacFirmware").text($(j).find("PacFirmware").text());
$(h).find("Memory").attr("RefreshRate",$(j).find("Memory").attr("RefreshRate"));$(h).find("Memory").text($(j).find("Memory").text());
d=$(h).find("MemoryItem");for(a=0;a<d.length;a++){b=$(d)[a].attributes.getNamedItem("Id").value;
$(h).find("MemoryItem[Id='"+b+"']").text($(j).find("MemoryItem[Id='"+b+"']").text());
}$(h).find("Assemblies").attr("Visible",$(j).find("Assemblies").attr("Visible"));
d=$(h).find("Assembly");for(a=0;a<d.length;a++){b=$(d)[a].getAttribute("Id").replace(/\\/g,"\\\\");
var f=$(h).find("Assembly[Id='"+b+"']");var g=$(j).find("Assembly[Id='"+b+"']");f.attr("Version",g.attr("Version"));
f.attr("ModDate",g.attr("ModDate"));}return h;};MOCK.saveSecuritySettings=function(l,f){var d=false;
var k=$(l).find("Data");var a=parseInt(k.find("Deleted").text(),10);var i=parseInt(k.find("UserLevel").text(),10);
var c=parseInt(k.find("Enabled").text(),10);var j=k.find("Username").text().toLowerCase();
var h=k.find("password").text();var b=CMN.dateToMilliseconds();var g=0;$.each(f,function(o,m){var n=parseInt(m.id.substr(3),10);
if(n>g){g=n;}if(m.username.toLowerCase()===j){m.password=h;m.enabled=c;m.userlevel=i;
m.deleted=a;m.datemodified=b;d=true;}});if(!d){var e={enabled:c,deleted:a,userlevel:i,datecreated:b,datemodified:b,password:h,username:CMN.toTitleCase(j),id:"id_"+(g+1),ipaddress:"",lastaccessed:null};
f.push(e);}return l;};MOCK.addValuesToXml=function(d,e){var a=$(e).find("*:eq(1)").children();
for(var b=0;b<a.length;b++){var c=a[b].nodeName;$(d).find(c).text($(e).find(c).text());
}return d;};