:: ----------------------------------------------------------------------------           
:: This command file is auto-generated by the 'pre-build command file in StaticContent. 
::                               
:: (c) 2013-2017 Parker Hannifin 
:: ----------------------------------------------------------------------------          
@echo off
set scrTmp=Y:\Tucson\trunk\ParkerWebCF\StaticContent\scripts\temp\
set scrDst=S:\Tucson\Build\Web\Inetpub\scripts\
echo.
echo.
call:GetDT dt
echo +- %dt% -- Post-deploy processing for ParkerWebCF "StaticContent" started. ----------------------+
echo.^|
echo ^| The following javascript files are being reset:
echo.^|
echo ^|  "%scrTmp%tucson\aboutinfo.js"...
echo. >"%scrTmp%tucson\aboutinfo.js"  
echo ^|  "%scrTmp%tucson\datetimesettings.js"...
echo. >"%scrTmp%tucson\datetimesettings.js"  
echo ^|  "%scrTmp%tucson\internetsettings.js"...
echo. >"%scrTmp%tucson\internetsettings.js"  
echo ^|  "%scrTmp%tucson\memoryinfo.js"...
echo. >"%scrTmp%tucson\memoryinfo.js"  
echo ^|  "%scrTmp%tucson\networksettings.js"...
echo. >"%scrTmp%tucson\networksettings.js"  
echo ^|  "%scrTmp%tucson\securitygrid.js"...
echo. >"%scrTmp%tucson\securitygrid.js"  
echo ^|  "%scrTmp%tucson\securitysettings.js"...
echo. >"%scrTmp%tucson\securitysettings.js"  
echo ^|  "%scrTmp%tucson\systemsettings.js"...
echo. >"%scrTmp%tucson\systemsettings.js"  
echo ^|  "%scrTmp%tucson\tucson.common.js"...
echo. >"%scrTmp%tucson\tucson.common.js"  
echo ^|  "%scrTmp%tucson\tucson.configtool.js"...
echo. >"%scrTmp%tucson\tucson.configtool.js"  
echo ^|  "%scrTmp%tucson\tucson.login.js"...
echo. >"%scrTmp%tucson\tucson.login.js"  
echo ^|  "%scrTmp%tucson\tucson.utils.js"...
echo. >"%scrTmp%tucson\tucson.utils.js"  
echo ^|  "%scrTmp%tucson\xpresssettings.js"...
echo. >"%scrTmp%tucson\xpresssettings.js"  
echo ^|  "%scrTmp%ui\jquery.ipaddress.js"...
echo. >"%scrTmp%ui\jquery.ipaddress.js"  
echo.^|
call:GetDT dt
echo +- %dt% -- Post-deploy processing for ParkerWebCF "StaticContent" completed. -------------------+
goto:EOF
:GetDT
set %1=%date% %time%
goto:EOF
