:: ----------------------------------------------------------------------------           
:: This command file is auto-generated by the 'pre-build command file in StaticContent. 
::                               
:: (c) 2013-2017 Parker Hannifin 
:: ----------------------------------------------------------------------------          
@echo off
set scrTmp=Y:\Tucson\trunk\ParkerWebCF\StaticContent\scripts\temp\
set scrDst=S:\Tucson\Build\Web\Inetpub\scripts\
echo.
echo.
call:GetDT dt
echo +- %dt% -- Post-build processing for ParkerWebCF "StaticContent" started. ----------------------+
echo.^|
if exist "S:\Tucson\Build\Web\Inetpub\StaticContent.dll" (
	echo.^|  Deleting extraneous StaticContent.dll from the target folder...
	del/q "S:\Tucson\Build\Web\Inetpub\StaticContent.dll"
)
echo.^|
goto SKIP 
echo ^|  Copying "%scrTmp%tucson\aboutinfo.js"    
echo ^|       to "%scrDst%tucson\aboutinfo.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\aboutinfo.js" "%scrDst%tucson\aboutinfo.js"
echo ^|  Copying "%scrTmp%tucson\datetimesettings.js"    
echo ^|       to "%scrDst%tucson\datetimesettings.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\datetimesettings.js" "%scrDst%tucson\datetimesettings.js"
echo ^|  Copying "%scrTmp%tucson\internetsettings.js"    
echo ^|       to "%scrDst%tucson\internetsettings.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\internetsettings.js" "%scrDst%tucson\internetsettings.js"
echo ^|  Copying "%scrTmp%tucson\memoryinfo.js"    
echo ^|       to "%scrDst%tucson\memoryinfo.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\memoryinfo.js" "%scrDst%tucson\memoryinfo.js"
echo ^|  Copying "%scrTmp%tucson\networksettings.js"    
echo ^|       to "%scrDst%tucson\networksettings.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\networksettings.js" "%scrDst%tucson\networksettings.js"
echo ^|  Copying "%scrTmp%tucson\securitygrid.js"    
echo ^|       to "%scrDst%tucson\securitygrid.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\securitygrid.js" "%scrDst%tucson\securitygrid.js"
echo ^|  Copying "%scrTmp%tucson\securitysettings.js"    
echo ^|       to "%scrDst%tucson\securitysettings.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\securitysettings.js" "%scrDst%tucson\securitysettings.js"
echo ^|  Copying "%scrTmp%tucson\systemsettings.js"    
echo ^|       to "%scrDst%tucson\systemsettings.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\systemsettings.js" "%scrDst%tucson\systemsettings.js"
echo ^|  Copying "%scrTmp%tucson\tucson.common.js"    
echo ^|       to "%scrDst%tucson\tucson.common.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\tucson.common.js" "%scrDst%tucson\tucson.common.js"
echo ^|  Copying "%scrTmp%tucson\tucson.configtool.js"    
echo ^|       to "%scrDst%tucson\tucson.configtool.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\tucson.configtool.js" "%scrDst%tucson\tucson.configtool.js"
echo ^|  Copying "%scrTmp%tucson\tucson.login.js"    
echo ^|       to "%scrDst%tucson\tucson.login.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\tucson.login.js" "%scrDst%tucson\tucson.login.js"
echo ^|  Copying "%scrTmp%tucson\tucson.utils.js"    
echo ^|       to "%scrDst%tucson\tucson.utils.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\tucson.utils.js" "%scrDst%tucson\tucson.utils.js"
echo ^|  Copying "%scrTmp%tucson\xpresssettings.js"    
echo ^|       to "%scrDst%tucson\xpresssettings.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%tucson\xpresssettings.js" "%scrDst%tucson\xpresssettings.js"
echo ^|  Copying "%scrTmp%ui\jquery.ipaddress.js"    
echo ^|       to "%scrDst%ui\jquery.ipaddress.js"... 
echo|set /p=^^^| & copy/y       "%scrTmp%ui\jquery.ipaddress.js" "%scrDst%ui\jquery.ipaddress.js"
echo.^|
:SKIP
echo ^| ===========================================================================================================
echo ^|  To fully test the PAC, run the following command file at least once 'post-deployment' on the CE device:   
echo.^|          "\Windows\Parker\Web\Inetpub\scripts\temp\docopy.cmd"                                                   
echo ^|  [This will allow full testing of the compressed javascript files which are used in the final release...]  
echo ^| ===========================================================================================================
echo.^|
echo.^|
call:GetDT dt
echo +- %dt% -- Post-build processing for ParkerWebCF "StaticContent" completed. --------------------+
echo.
echo.
goto:EOF
:GetDT
set %1=%date% %time%
goto:EOF
